name: 'Automatic tweet new post on create'
description: "Automatically tweets the new post to Twitter"
author: "ruchernchong"
inputs:
  hostname:
    description: 'The hostname of the post to be tweeted'
    required: true
  path:
    description: 'The path of the folder containing your posts'
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
