on: [push]

jobs:
  test_tweet_item:
    runs-on: ubuntu-latest
    name: Tweeting new post to Twitter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tweet Post Action
        uses: ./
        with:
          hostname: https://ruchern.xyz
          path: '/posts'
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}